substitutions:
  device_name: owl-sensor
  device_id: owl-sensor
  friendly_name: Owl sensor
  device_description: ESP32
  icon: "mdi:motion-sensor"

esphome:
  name: "${device_name}"
  friendly_name: ${friendly_name}
  platformio_options:
    board_build.f_cpu: 80000000L  # Run at 80MHz to reduce power
  on_boot:
    priority: 600
    then:
      - lambda: |-
          // Disable brownout detector
          #include "soc/rtc_cntl_reg.h"
          #include "soc/soc.h"
          WRITE_PERI_REG(RTC_CNTL_BROWN_OUT_REG, 0);

esp32:
  board: nodemcu-32s
  framework:
    type: arduino
    version: recommended
  variant: esp32

# Enable logging
logger:
  baud_rate: 0  # Disable UART logging to reduce startup power

# Enable Home Assistant API
api:
  encryption:
    key: !secret esp_encryption_key

ota:
 - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: !secret fast_connect
  domain: .lan
  output_power: 8.5dB  # Reduced WiFi TX power to lower startup surge
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name}"
    password: !secret ap_mode_pw

captive_portal:

external_components:
  - source: components
    refresh: 5s

uart:
  - id: htzsafe_uart
    tx_pin: GPIO17
    rx_pin: GPIO16
    baud_rate: 9600

htzsafe:
  id: owl_sensor
  uart_id: htzsafe_uart
  devices:
    - id: driveway_sensor
      name: "Driveway"
      identifier: 0xe864
    - id: mailbox_sensor
      name: "Mailbox"
      identifier: 0xe76a

button:
  - platform: restart
    name: "Restart"

sensor:
  - platform: wifi_signal
    name: "WiFi signal"
    update_interval: 60s
